### ISSUE TITLE
mac m2 安装Can't pickle <class 'sqlalchemy.orm.session.Session'>: it's not the same object as sqlalchemy.orm.session.Session

### ISSUE THREAD

**Issue by hailiang-bai** [gangly/datafaker#112]
python 3.8.13 和python3.11 都报相同的错

**Comment by hailiang-bai** [comment]
Traceback (most recent call last):
  File "/Users/mrbai/opt/software/anaconda3/lib/python3.11/site-packages/datafaker/cli.py", line 91, in main
    db.do_fake()
  File "/Users/mrbai/opt/software/anaconda3/lib/python3.11/site-packages/datafaker/utils.py", line 72, in wrapper
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mrbai/opt/software/anaconda3/lib/python3.11/site-packages/datafaker/dbs/basedb.py", line 99, in do_fake
    producer.start()
  File "/Users/mrbai/opt/software/anaconda3/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/Users/mrbai/opt/software/anaconda3/lib/python3.11/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mrbai/opt/software/anaconda3/lib/python3.11/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/mrbai/opt/software/anaconda3/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/mrbai/opt/software/anaconda3/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/mrbai/opt/software/anaconda3/lib/python3.11/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/mrbai/opt/software/anaconda3/lib/python3.11/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'sqlalchemy.orm.session.Session'>: it's not the same object as sqlalchemy.orm.session.Session

Can't pickle <class 'sqlalchemy.orm.session.Session'>: it's not the same object as sqlalchemy.orm.session.Session

**Comment by labilixin** [comment]
我这边使用docker创建一个python环境可以运行。
