### ISSUE TITLE
按照举例来操作生成数据报错啊

### ISSUE THREAD

**Issue by xie-jinfen** [gangly/datafaker#14]
File "D:\Python\Python36\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd7 in position 9: invalid continuation byte

'utf-8' codec can't decode byte 0xd7 in position 9: invalid continuation byte
Exception ignored in: <bound method RdbDB.__del__ of <datafaker.dbs.rdbdb.RdbDB object at 0x0000018E8E5F0518>>
Traceback (most recent call last):
  File "D:\Python\Python36\lib\site-packages\datafaker\dbs\rdbdb.py", line 14, in __del__
    self.session.close()
AttributeError: 'RdbDB' object has no attribute 'session'

**Comment by gangly** [comment]
请注意看wiki ， 加上names.txt文件了吗

**Comment by gangly** [comment]
能提供下更多的错误信息吗，  请查看下按照例子文档  有names.txt文件吗

**Comment by xie-jinfen** [comment]
已经解决，编码格式问题
