### ISSUE TITLE
造kafka数据报错：TypeError: fake_column() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by xie-jinfen** [gangly/datafaker#15]
[root@node03 bin]# datafaker kafka node01:6667 test4 1 --meta meta.txt --outprint
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/datafaker/cli.py", line 78, in main
    db.do_fake()
  File "/usr/local/lib/python2.7/site-packages/datafaker/utils.py", line 72, in wrapper
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/datafaker/dbs/kafkadb.py", line 26, in do_fake
    lines = self.fake_column()
TypeError: fake_column() takes exactly 2 arguments (1 given)

fake_column() takes exactly 2 arguments (1 given)

**Comment by gangly** [comment]
bug已修复，请使用最新版本0.6.4
