### ISSUE TITLE
windows执行datafaker报错

### ISSUE THREAD

**Issue by Annadong1106** [gangly/datafaker#24]
python版本：3.6.8
datafaker版本：0.6.4
在执行【使用举例.md】中向mysql造数时候，报如下错误：
---------------------------------------------------------------------------------
D:\datafaker>datafaker rdb mysqlclient://root:root@localhost:3600/test?charset=utf8 stu 10 --outprint --meta meta.txt --outspliter ',,'
Traceback (most recent call last):
  File "D:\python\lib\site-packages\datafaker\cli.py", line 77, in main
    db = load_db_class(args.dbtype)(args)
  File "D:\python\lib\site-packages\datafaker\dbs\basedb.py", line 18, in __init__
    self.schema = self.parse_schema()
  File "D:\python\lib\site-packages\datafaker\dbs\basedb.py", line 127, in parse_schema
    schema = self.parse_meta_schema()
  File "D:\python\lib\site-packages\datafaker\dbs\basedb.py", line 137, in parse_meta_schema
    rows = self.construct_meta_rows()
  File "D:\python\lib\site-packages\datafaker\dbs\basedb.py", line 201, in construct_meta_rows
    lines = read_file_lines(filepath)
  File "D:\python\lib\site-packages\datafaker\utils.py", line 84, in read_file_lines
    lines = fp.read().splitlines()
  File "D:\python\lib\codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd7 in position 9: invalid continuation byte

'utf-8' codec can't decode byte 0xd7 in position 9: invalid continuation byte
Exception ignored in: <bound method RdbDB.__del__ of <datafaker.dbs.rdbdb.RdbDB object at 0x000002171485B6D8>>
Traceback (most recent call last):
  File "D:\python\lib\site-packages\datafaker\dbs\rdbdb.py", line 14, in __del__
    self.session.close()
AttributeError: 'RdbDB' object has no attribute 'session'
@gangly 麻烦您看一下是什么问题？

**Comment by gangly** [comment]
用最新版本0.7.0试试

**Comment by Annadong1106** [comment]
> 用最新版本0.7.0试试

更新到0.7.0了，还是报错欸，一样的错误

**Comment by gangly** [comment]
> > 用最新版本0.7.0试试
> 
> 更新到0.7.0了，还是报错欸，一样的错误

bug已修复，请更新到0.7.1
