### ISSUE TITLE
使用python3.7运行报错：No module named 'MySQLdb'

### ISSUE THREAD

**Issue by WeakeyZ** [gangly/datafaker#30]
Python版本：3.7.6
meta文件内容：
person_no||int||auto increament person_no[:inc(person_no,20201000)]
school_code||varchar(20)||school_code[:enum(12440104455354382L)]
name||varchar(20)||name
sex||varchar(5)||sex[:enum(男,女)]
person_role||int||person_role[:enum(1,2)]
grade_no||int||grade_no size[:enum(1,2,3,4,5,6)]
class_no||int||class_no[:enum(1,2,3,4,5,6,7,8,9)]
face_id||varchar(20)||face_id [:inc(700044010402000027202005080000000002,1)]
脚本命令： datafaker mysql mysql+mysqldb://root:root@localhost:3306/medical_door tb_person 10 --outprint --meta person_meta.txt --outspliter _

**Comment by WeakeyZ** [comment]
以下是报错信息：
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\datafaker-0.7.2-py3.7.egg\datafaker\cli.py", line 89, in main
    db = load_db_class(args.dbtype)(args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\datafaker-0.7.2-py3.7.egg\datafaker\dbs\basedb.py", line 40, in __init__
    self.init()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\datafaker-0.7.2-py3.7.egg\datafaker\dbs\rdbdb.py", line 11, in init
    self.session = load_sqlalchemy(self.args.connect)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\datafaker-0.7.2-py3.7.egg\datafaker\drivers.py", line 14, in load_sqlalchemy
    engine = create_engine(connet, pool_recycle=1800)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy-1.3.8-py3.7-win-amd64.egg\sqlalchemy\engine\__init__.py", line 456, in create_engine
    return strategy.create(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy-1.3.8-py3.7-win-amd64.egg\sqlalchemy\engine\strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy-1.3.8-py3.7-win-amd64.egg\sqlalchemy\dialects\mysql\mysqldb.py", line 118, in dbapi
    return __import__("MySQLdb")
ModuleNotFoundError: No module named 'MySQLdb'

No module named 'MySQLdb'

**Comment by gangly** [comment]
> 以下是报错信息：
> Traceback (most recent call last):
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\datafaker-0.7.2-py3.7.egg\datafaker\cli.py", line 89, in main
> db = load_db_class(args.dbtype)(args)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\datafaker-0.7.2-py3.7.egg\datafaker\dbs\basedb.py", line 40, in **init**
> self.init()
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\datafaker-0.7.2-py3.7.egg\datafaker\dbs\rdbdb.py", line 11, in init
> self.session = load_sqlalchemy(self.args.connect)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\datafaker-0.7.2-py3.7.egg\datafaker\drivers.py", line 14, in load_sqlalchemy
> engine = create_engine(connet, pool_recycle=1800)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy-1.3.8-py3.7-win-amd64.egg\sqlalchemy\engine__init__.py", line 456, in create_engine
> return strategy.create(*args, **kwargs)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy-1.3.8-py3.7-win-amd64.egg\sqlalchemy\engine\strategies.py", line 87, in create
> dbapi = dialect_cls.dbapi(**dbapi_args)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy-1.3.8-py3.7-win-amd64.egg\sqlalchemy\dialects\mysql\mysqldb.py", line 118, in dbapi
> return **import**("MySQLdb")
> ModuleNotFoundError: No module named 'MySQLdb'
> 
> No module named 'MySQLdb'

请仔细查看安装文档，对于不同数据源，需要再安装对应数据源的python库

**Comment by WeakeyZ** [comment]
没看仔细，使用pip install mysqlclient成功解决

**Comment by WeakeyZ** [comment]
![image](https://user-images.githubusercontent.com/48713166/82305453-36dee700-99f0-11ea-8158-3f2ab1f3a16b.png)
输出到控制台出现无限刷乱码的问题，请问怎么解决？
meta文档内容：
record_id||int||auto increament record_id[:inc(record_id,20201001)]
record_time||date||record_time[:datetime(2020-01-01, 2020-01-05)]
record_temperature||decimal(3,1)||record_temperature[:decimal(3,1,1)]
person_no||varchar(10)||person_no[:string(20201000,20201200)]

**Comment by gangly** [comment]
> ![image](https://raw.githubusercontent.com/WeakeyZ/mdPic/master/mobileDoctor/20200519165538.png)
> 
> 输出到控制台出现无限刷乱码的问题，请问怎么解决？
> meta文档内容：
> record_id||int||auto increament record_id[:inc(record_id,20201001)]
> record_time||date||record_time[:datetime(2020-01-01, 2020-01-05)]
> record_temperature||decimal(3,1)||record_temperature[:decimal(3,1,1)]
> person_no||varchar(10)||person_no[:string(20201000,20201200)]

你写文件，看没有没有乱码

**Comment by gangly** [comment]
> > ![image](https://raw.githubusercontent.com/WeakeyZ/mdPic/master/mobileDoctor/20200519165538.png)
> > 输出到控制台出现无限刷乱码的问题，请问怎么解决？
> > meta文档内容：
> > record_id||int||auto increament record_id[:inc(record_id,20201001)]
> > record_time||date||record_time[:datetime(2020-01-01, 2020-01-05)]
> > record_temperature||decimal(3,1)||record_temperature[:decimal(3,1,1)]
> > person_no||varchar(10)||person_no[:string(20201000,20201200)]
> 
> 你写文件，看没有没有乱码

string标记没用对，产生了20201000长度的字符串

**Comment by WeakeyZ** [comment]
> > > ![image](https://raw.githubusercontent.com/WeakeyZ/mdPic/master/mobileDoctor/20200519165538.png)
> > > 输出到控制台出现无限刷乱码的问题，请问怎么解决？
> > > meta文档内容：
> > > record_id||int||auto increament record_id[:inc(record_id,20201001)]
> > > record_time||date||record_time[:datetime(2020-01-01, 2020-01-05)]
> > > record_temperature||decimal(3,1)||record_temperature[:decimal(3,1,1)]
> > > person_no||varchar(10)||person_no[:string(20201000,20201200)]
> > 
> > 
> > 你写文件，看没有没有乱码
> 
> string标记没用对，产生了20201000长度的字符串

string(min,max)这里表示的不是min到max的范围的值？比如2000到4000内的值string(2000,4000)?

**Comment by gangly** [comment]
> > > > ![image](https://raw.githubusercontent.com/WeakeyZ/mdPic/master/mobileDoctor/20200519165538.png)
> > > > 输出到控制台出现无限刷乱码的问题，请问怎么解决？
> > > > meta文档内容：
> > > > record_id||int||auto increament record_id[:inc(record_id,20201001)]
> > > > record_time||date||record_time[:datetime(2020-01-01, 2020-01-05)]
> > > > record_temperature||decimal(3,1)||record_temperature[:decimal(3,1,1)]
> > > > person_no||varchar(10)||person_no[:string(20201000,20201200)]
> > > 
> > > 
> > > 你写文件，看没有没有乱码
> > 
> > 
> > string标记没用对，产生了20201000长度的字符串
> 
> string(min,max)这里表示的不是min到max的范围的值？比如2000到4000内的值string(2000,4000)?

请仔细读文档，string(min,max)表示产生min到max个字符的字符串
产生数字用，
random_int | 随机数字  可设置范围，可以通过设置min,max来设置，默认0~9999，例如random_int(1,100)

**Comment by WeakeyZ** [comment]
> > > > > ![image](https://raw.githubusercontent.com/WeakeyZ/mdPic/master/mobileDoctor/20200519165538.png)
> > > > > 输出到控制台出现无限刷乱码的问题，请问怎么解决？
> > > > > meta文档内容：
> > > > > record_id||int||auto increament record_id[:inc(record_id,20201001)]
> > > > > record_time||date||record_time[:datetime(2020-01-01, 2020-01-05)]
> > > > > record_temperature||decimal(3,1)||record_temperature[:decimal(3,1,1)]
> > > > > person_no||varchar(10)||person_no[:string(20201000,20201200)]
> > > > 
> > > > 
> > > > 你写文件，看没有没有乱码
> > > 
> > > 
> > > string标记没用对，产生了20201000长度的字符串
> > 
> > 
> > string(min,max)这里表示的不是min到max的范围的值？比如2000到4000内的值string(2000,4000)?
> 
> 请仔细读文档，string(min,max)表示产生min到max个字符的字符串
> 产生数字用，
> random_int | 随机数字 可设置范围，可以通过设置min,max来设置，默认0~9999，例如random_int(1,100)

抱歉，理解有误

**Comment by WeakeyZ** [comment]
![image](https://raw.githubusercontent.com/WeakeyZ/mdPic/master/mobileDoctor/20200519174119.png)
meta文档内容：
record_id||int||auto increament record_id[:inc(record_id,44)]
record_time||datetime||record_time[:datetime(2020-01-01 10:10:00,2020-01-10 10:10:00))]
record_temperature||decimal(3,1)||record_temperature[:decimal(3,1)]
person_no||varchar(10)||person_no[:random_int(20201001,20201200)]

这是产生的数据，但是时间不是输出的2020-01-01 10:10:00~2020-01-10 10:10:00之间的值，想问问作者这个输出范围内随机时间怎么实现，还有想输出类似于体温数据，比如36.5~37.5之间的随机数值，又如何实现，最后两个功能点了，很抱歉打扰作者

**Comment by gangly** [comment]
已经增加时间和浮点范围取值，请使用0.7.3版本和最新文档
