### ISSUE TITLE
window bug?

### ISSUE THREAD

**Issue by zack542** [gangly/datafaker#32]
`
C:\Users\leile\Desktop>datafaker mysql mysql+mysqldb://root:Hd@123456@localhost:3306/test stu 10  --meta meta.txt
Traceback (most recent call last):
  File "build\bdist.win-amd64\egg\datafaker\cli.py", line 89, in main
    db = load_db_class(args.dbtype)(args)
  File "build\bdist.win-amd64\egg\datafaker\cli.py", line 79, in load_db_class
    module = __import__(pkgname, fromlist=(classname))
  File "build\bdist.win-amd64\egg\datafaker\dbs\mysqldb.py", line 3, in <module>
  File "build\bdist.win-amd64\egg\datafaker\dbs\basedb.py", line 7, in <module>
  File "build\bdist.win-amd64\egg\datafaker\compat.py", line 41, in <module>
  File "build\bdist.win-amd64\egg\datafaker\multithreading.py", line 6, in <module>
ImportError: No module named queue

No module named queue`

**Comment by gangly** [comment]
> `
> C:\Users\leile\Desktop>datafaker mysql mysql+mysqldb://root:Hd@123456@localhost:3306/test stu 10 --meta meta.txt
> Traceback (most recent call last):
> File "build\bdist.win-amd64\egg\datafaker\cli.py", line 89, in main
> db = load_db_class(args.dbtype)(args)
> File "build\bdist.win-amd64\egg\datafaker\cli.py", line 79, in load_db_class
> module = **import**(pkgname, fromlist=(classname))
> File "build\bdist.win-amd64\egg\datafaker\dbs\mysqldb.py", line 3, in
> File "build\bdist.win-amd64\egg\datafaker\dbs\basedb.py", line 7, in
> File "build\bdist.win-amd64\egg\datafaker\compat.py", line 41, in
> File "build\bdist.win-amd64\egg\datafaker\multithreading.py", line 6, in
> ImportError: No module named queue
> 
> No module named queue`

试下最新版本0.7.3
