### ISSUE TITLE
运行脚本时报错

### ISSUE THREAD

**Issue by yzft1991** [gangly/datafaker#33]
C:\Users\yzft1>datafaker mysql mysql+mysqldb://root:zgadmin@192.168.1.237:3307/population prop_knowledge_patent 20 --meta prop_knowledge_patent2.txt
Traceback (most recent call last):
  File "C:\Users\yzft1\AppData\Local\Programs\Python\Python36\lib\site-packages\datafaker\cli.py", line 89, in main
    db = load_db_class(args.dbtype)(args)
  File "C:\Users\yzft1\AppData\Local\Programs\Python\Python36\lib\site-packages\datafaker\dbs\basedb.py", line 28, in __init__
    self.queue = compat.Queue(maxsize=MAX_QUEUE_SIZE)
AttributeError: module 'datafaker.compat' has no attribute 'Queue'

module 'datafaker.compat' has no attribute 'Queue'

**Comment by Dz318** [comment]
我也是提示这个，环境:python3.7.6，datafaker0.7.3，求助 @gangly

**Comment by gangly** [comment]
> C:\Users\yzft1>datafaker mysql mysql+mysqldb://root:zgadmin@192.168.1.237:3307/population prop_knowledge_patent 20 --meta prop_knowledge_patent2.txt
> Traceback (most recent call last):
> File "C:\Users\yzft1\AppData\Local\Programs\Python\Python36\lib\site-packages\datafaker\cli.py", line 89, in main
> db = load_db_class(args.dbtype)(args)
> File "C:\Users\yzft1\AppData\Local\Programs\Python\Python36\lib\site-packages\datafaker\dbs\basedb.py", line 28, in **init**
> self.queue = compat.Queue(maxsize=MAX_QUEUE_SIZE)
> AttributeError: module 'datafaker.compat' has no attribute 'Queue'
> 
> module 'datafaker.compat' has no attribute 'Queue'



> 我也是提示这个，环境:python3.7.6，datafaker0.7.3，求助 @gangly

问题已修复，请使用0.7.4版本
