### ISSUE TITLE
windows7系统下载后无法使用，并且连接oracle数据库无法支持批量插入，只能同时插入一条

### ISSUE THREAD

**Issue by a3733092** [gangly/datafaker#4]
windows7系统，py3.5下载后无法使用命令，cx_oracle插入语法不支持insert into table_name(column) values (),(),()，希望作者能帮忙解决一下。谢谢~

**Comment by gangly** [comment]
报什么错，把错误贴出来呢

**Comment by a3733092** [comment]
刚在win7上替换了github最新的代码，执行命令datafaker mysql mysql+mysqldb://root:root@localhost:3306/test3 stu 10 还是报错如下：
 File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\MySQLdb\__init__.py", line 19, in <module>
import _mysql
ortError: DLL load failed: 找不到指定的模块。
连接oracle是在linux服务器上执行的，错误请等我找一下。

**Comment by gangly** [comment]
用的mysql还是oracle数据库？看错误是mysql数据库驱动包没安装好

**Comment by a3733092** [comment]
上面那个是mysql，这个是linux上执行的datafaker mysql oracle+cx_oracle://xxx:xxx@xxxx /orcl xxx 5 --meta meta3.txt 命令，报错如下：
   self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/datafaker/dbs/basedb.py", line 97, in save
    self.save_data(lines)
  File "/usr/lib/python2.7/site-packages/datafaker/dbs/rdb.py", line 32, in save_data
    self.session.execute(sql)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 1269, in execute
    clause, params or {}
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py", line 553, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (cx_Oracle.DatabaseError) ORA-00933: SQL command not properly ended
[SQL: insert into TEST1 (GRADE) values (9.20510620579e+14),(16.7440451),(62702872159.0),(6252102.7043),(7969768170.92)]
(Background on this error at: http://sqlalche.me/e/4xp6)
其实这条SQL语句是在oracle下执行不通过的。

**Comment by gangly** [comment]
datafaker rdb oracle+cx_oracle://xxx:xxx@xxxx /orcl xxx 5 --meta meta3.txt 试试

**Comment by a3733092** [comment]
还是报错。。
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/datafaker/cli.py", line 77, in main
    db = load_db_class(args.dbtype)(args)
  File "/usr/lib/python2.7/site-packages/datafaker/cli.py", line 67, in load_db_class
    module = __import__(pkgname, fromlist=(classname))
ImportError: No module named rdbdb

**Comment by gangly** [comment]
datafaker --version看看版本号是多少

**Comment by a3733092** [comment]
0.3.7

**Comment by gangly** [comment]
最新版本是0.4.1了，
用pip install datafaker --upgrade更新下
https://pypi.org/project/datafaker/

**Comment by a3733092** [comment]
升级了现在提示[root@localhost ~]# datafaker -version
: 没有那个文件或目录
是不是最新版本不支持python2.7了。。

**Comment by gangly** [comment]
--version

**Comment by a3733092** [comment]
也是一样的。。感觉要回退回去了

**Comment by a3733092** [comment]
大佬，win7连oracle还是有问题，字段还会出现乱码问题，而且批量插入也还是mysql的插入方式。这个地方感觉可以加个判断，oracle批量插入就换一种插入语句

ackages\sqlalchemy\engine\base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\sqlalchemy\engine\base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\sqlalchemy\engine\base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\sqlalchemy\engine\base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-p
ackages\sqlalchemy\engine\default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00933: SQL command n
ot properly ended
[SQL: insert into TEST1 (锘縞rade) values (6347492234512.6),(192224.8864529),(-5
895368719.2),(-1330873.77947261),(-559.31134895)]
(Background on this error at: http://sqlalche.me/e/4xp6)

**Comment by gangly** [comment]
谢谢反馈，没有用到过oracle，一直没测试。
试试这种方式：
datafaker file 
把生成的测试数据写到文件里面，然后通过工具导入到oracle

**Comment by gangly** [comment]
或者指定batch参数为1，这样就是一条一条插入数据

**Comment by a3733092** [comment]
好像还有乱码问题。。grade，它第一个字母会乱码

sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00904: "锘縞RADE": i
nvalid identifier
[SQL: insert into TEST1 (锘縞rade) values (-1394537595550.13)]
(Background on this error at: http://sqlalche.me/e/4xp6)

time used: 0.229 s

**Comment by gangly** [comment]
> windows7系统，py3.5下载后无法使用命令，cx_oracle插入语法不支持insert into table_name(column) values (),(),()，希望作者能帮忙解决一下。谢谢~

oracle多条写入已支持，请使用最新版本
