### ISSUE TITLE
你好，执行文件写入到文件时报错

### ISSUE THREAD

**Issue by FengZhengHai** [gangly/datafaker#40]
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
time used: 0.110 s

**Comment by FengZhengHai** [comment]
@gangly 求助

**Comment by Sanchez2020** [comment]
@FengZhengHai 请问如何解决的问题？

**Comment by AlexBdd** [comment]
苹果操作系统：macOS catalina 10.15.7
(base) ➜  Desktop python3 -V                          
Python 3.8.5
(base) ➜  Desktop 
(base) ➜  Desktop datafaker file /Users/dbok/Desktop out.txt 10 --meta user_meta.txt --outprint                                             
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/opt/anaconda3/lib/python3.8/site-packages/datafaker/dbs/filedb.py", line 5, in <module>
    from datafaker.compat import safe_encode
  File "/opt/anaconda3/lib/python3.8/site-packages/datafaker/compat.py", line 46, in <module>
    List = multiprocessing.Manager().list
  File "/opt/anaconda3/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/opt/anaconda3/lib/python3.8/multiprocessing/managers.py", line 579, in start
    self._process.start()
  File "/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/anaconda3/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/anaconda3/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/opt/anaconda3/lib/python3.8/site-packages/datafaker/dbs/filedb.py", line 5, in <module>
    from datafaker.compat import safe_encode
  File "/opt/anaconda3/lib/python3.8/site-packages/datafaker/compat.py", line 46, in <module>
    List = multiprocessing.Manager().list
  File "/opt/anaconda3/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/opt/anaconda3/lib/python3.8/multiprocessing/managers.py", line 579, in start
    self._process.start()
  File "/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/anaconda3/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/anaconda3/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/opt/anaconda3/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
time used: 0.415 s
(base) ➜  Desktop
