### ISSUE TITLE
你好，文件写入文件时报错

### ISSUE THREAD

**Issue by FengZhengHai** [gangly/datafaker#42]
% datafaker file . out.txt 10 --meta mg_mock_meta.txt   
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/datafaker-0.7.4-py3.8.egg/datafaker/cli.py", line 89, in main
    db = load_db_class(args.dbtype)(args)
  File "/usr/local/lib/python3.8/site-packages/datafaker-0.7.4-py3.8.egg/datafaker/cli.py", line 79, in load_db_class
    module = __import__(pkgname, fromlist=(classname))
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/site-packages/datafaker-0.7.4-py3.8.egg/datafaker/dbs/filedb.py", line 5, in <module>
    from datafaker.compat import safe_encode
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/site-packages/datafaker-0.7.4-py3.8.egg/datafaker/compat.py", line 46, in <module>
    List = multiprocessing.Manager().list
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/managers.py", line 579, in start
    self._process.start()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 183, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '__main__' has no attribute '__spec__'

module '__main__' has no attribute '__spec__'

**Comment by gangly** [comment]
> % datafaker file . out.txt 10 --meta mg_mock_meta.txt
> Traceback (most recent call last):
> File "/usr/local/lib/python3.8/site-packages/datafaker-0.7.4-py3.8.egg/datafaker/cli.py", line 89, in main
> db = load_db_class(args.dbtype)(args)
> File "/usr/local/lib/python3.8/site-packages/datafaker-0.7.4-py3.8.egg/datafaker/cli.py", line 79, in load_db_class
> module = **import**(pkgname, fromlist=(classname))
> File "", line 991, in _find_and_load
> File "", line 975, in _find_and_load_unlocked
> File "", line 655, in _load_unlocked
> File "", line 618, in _load_backward_compatible
> File "", line 259, in load_module
> File "/usr/local/lib/python3.8/site-packages/datafaker-0.7.4-py3.8.egg/datafaker/dbs/filedb.py", line 5, in
> from datafaker.compat import safe_encode
> File "", line 991, in _find_and_load
> File "", line 975, in _find_and_load_unlocked
> File "", line 655, in _load_unlocked
> File "", line 618, in _load_backward_compatible
> File "", line 259, in load_module
> File "/usr/local/lib/python3.8/site-packages/datafaker-0.7.4-py3.8.egg/datafaker/compat.py", line 46, in
> List = multiprocessing.Manager().list
> File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 57, in Manager
> m.start()
> File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/managers.py", line 579, in start
> self._process.start()
> File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
> self._popen = self._Popen(self)
> File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
> return Popen(process_obj)
> File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in **init**
> super().**init**(process_obj)
> File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in **init**
> self._launch(process_obj)
> File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
> prep_data = spawn.get_preparation_data(process_obj._name)
> File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 183, in get_preparation_data
> main_mod_name = getattr(main_module.**spec**, "name", None)
> AttributeError: module '**main**' has no attribute '**spec**'
> 
> module '**main**' has no attribute '**spec**'

3.8版本还没测试过，建议换到3.7试试

**Comment by shenxiaoqi-1028** [comment]
> > % datafaker file . out.txt 10 --meta mg_mock_meta.txt
> > Traceback (most recent call last):
> > File "/usr/local/lib/python3.8/site-packages/datafaker-0.7.4-py3.8.egg/datafaker/cli.py", line 89, in main
> > db = load_db_class(args.dbtype)(args)
> > File "/usr/local/lib/python3.8/site-packages/datafaker-0.7.4-py3.8.egg/datafaker/cli.py", line 79, in load_db_class
> > module = **import**(pkgname, fromlist=(classname))
> > File "", line 991, in _find_and_load
> > File "", line 975, in _find_and_load_unlocked
> > File "", line 655, in _load_unlocked
> > File "", line 618, in _load_backward_compatible
> > File "", line 259, in load_module
> > File "/usr/local/lib/python3.8/site-packages/datafaker-0.7.4-py3.8.egg/datafaker/dbs/filedb.py", line 5, in
> > from datafaker.compat import safe_encode
> > File "", line 991, in _find_and_load
> > File "", line 975, in _find_and_load_unlocked
> > File "", line 655, in _load_unlocked
> > File "", line 618, in _load_backward_compatible
> > File "", line 259, in load_module
> > File "/usr/local/lib/python3.8/site-packages/datafaker-0.7.4-py3.8.egg/datafaker/compat.py", line 46, in
> > List = multiprocessing.Manager().list
> > File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 57, in Manager
> > m.start()
> > File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/managers.py", line 579, in start
> > self._process.start()
> > File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
> > self._popen = self._Popen(self)
> > File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
> > return Popen(process_obj)
> > File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in **init**
> > super().**init**(process_obj)
> > File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in **init**
> > self._launch(process_obj)
> > File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
> > prep_data = spawn.get_preparation_data(process_obj._name)
> > File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 183, in get_preparation_data
> > main_mod_name = getattr(main_module.**spec**, "name", None)
> > AttributeError: module '**main**' has no attribute '**spec**'
> > module '**main**' has no attribute '**spec**'
> 
> 3.8版本还没测试过，建议换到3.7试试

3.7也是同样问题
