### ISSUE TITLE
打印输出没问题，但是录入数据库报错了，macos/datafaker新版

### ISSUE THREAD

**Issue by roczzz** [gangly/datafaker#43]
[root@localhost ~]#  datafaker mysql mysql+mysqldb://root:123456@localhost:3306/ant_3.0_qm t_account_detail 10  --meta tad.txt
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/datafaker/dbs/basedb.py", line 122, in save
    self.save_data(lines)
  File "/usr/lib/python2.7/site-packages/datafaker/dbs/rdbdb.py", line 26, in save_data
    self.save_other_rdb(lines, names_format, column_names)
  File "/usr/lib/python2.7/site-packages/datafaker/dbs/rdbdb.py", line 42, in save_other_rdb
    self.session.execute(sql)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1269, in execute
    clause, params or {}
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib/python2.7/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "/usr/lib/python2.7/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 724, in _read_query_result
    result.read()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "/usr/lib/python2.7/site-packages/pymysql/protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
ProgrammingError: (pymysql.err.ProgrammingError) (1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '19:53:46,1384292845,0,569193),(15,18,2,'\u5546\u54c1\u8d2d\u4e70','65628319757403516',655645' at line 1")
[SQL: insert into t_account_detail (account_detail_id,shop_id,detail_type,description,biz_no,detail_amount,created_at,deleted_at,flag,avialable_amount) values (14,17,1,'\u5546\u54c1\u51fa\u552e','34250527876847164',691106,2020-08-27 19:53:46,1384292845,0,569193),(15,18,2,'\u5546\u54c1\u8d2d\u4e70','65628319757403516',655645,2020-08-27 19:53:46,350582394,0,110706),(16,19,1,'\u5546\u54c1\u51fa\u552e','19636796119968741',808004,2020-08-27 19:53:46,1256861491,0,466446),(17,20,2,'\u5546\u54c1\u8d2d\u4e70','46234490332455651',659574,2020-08-27 19:53:46,486638023,0,178019),(18,21,1,'\u5546\u54c1\u51fa\u552e','49266513315780232',743029,2020-08-27 19:53:46,717553851,0,246508),(19,22,2,'\u5546\u54c1\u8d2d\u4e70','90561178200881606',197382,2020-08-27 19:53:46,809470599,0,821661),(20,23,1,'\u5546\u54c1\u51fa\u552e','47997281259358174',232968,2020-08-27 19:53:46,1356754672,0,883010),(21,24,2,'\u5546\u54c1\u8d2d\u4e70','77079434011691921',162385,2020-08-27 19:53:46,1260205987,0,787554),(22,25,1,'\u5546\u54c1\u51fa\u552e','32080318843531665',429457,2020-08-27 19:53:46,42826607,0,557156),(23,26,2,'\u5546\u54c1\u8d2d\u4e70','15619744594723433',865789,2020-08-27 19:53:46,334998537,0,119933)]
(Background on this error at: http://sqlalche.me/e/f405)

**Comment by gangly** [comment]
> [root@localhost ~]# datafaker mysql mysql+mysqldb://root:123456@localhost:3306/ant_3.0_qm t_account_detail 10 --meta tad.txt
> Process Process-4:
> Traceback (most recent call last):
> File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
> self.run()
> File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
> self._target(*self._args, **self._kwargs)
> File "/usr/lib/python2.7/site-packages/datafaker/dbs/basedb.py", line 122, in save
> self.save_data(lines)
> File "/usr/lib/python2.7/site-packages/datafaker/dbs/rdbdb.py", line 26, in save_data
> self.save_other_rdb(lines, names_format, column_names)
> File "/usr/lib/python2.7/site-packages/datafaker/dbs/rdbdb.py", line 42, in save_other_rdb
> self.session.execute(sql)
> File "/usr/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1269, in execute
> clause, params or {}
> File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
> return meth(self, multiparams, params)
> File "/usr/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
> return connection._execute_clauseelement(self, multiparams, params)
> File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
> distilled_params,
> File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
> e, statement, parameters, cursor, context
> File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
> util.raise_from_cause(sqlalchemy_exception, exc_info)
> File "/usr/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
> reraise(type(exception), exception, tb=exc_tb, cause=cause)
> File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
> cursor, statement, parameters, context
> File "/usr/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
> cursor.execute(statement, parameters)
> File "/usr/lib/python2.7/site-packages/pymysql/cursors.py", line 163, in execute
> result = self._query(query)
> File "/usr/lib/python2.7/site-packages/pymysql/cursors.py", line 321, in _query
> conn.query(q)
> File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 505, in query
> self._affected_rows = self._read_query_result(unbuffered=unbuffered)
> File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 724, in _read_query_result
> result.read()
> File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 1069, in read
> first_packet = self.connection._read_packet()
> File "/usr/lib/python2.7/site-packages/pymysql/connections.py", line 676, in _read_packet
> packet.raise_for_error()
> File "/usr/lib/python2.7/site-packages/pymysql/protocol.py", line 223, in raise_for_error
> err.raise_mysql_exception(self._data)
> File "/usr/lib/python2.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
> raise errorclass(errno, errval)
> ProgrammingError: (pymysql.err.ProgrammingError) (1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '19:53:46,1384292845,0,569193),(15,18,2,'\u5546\u54c1\u8d2d\u4e70','65628319757403516',655645' at line 1")
> [SQL: insert into t_account_detail (account_detail_id,shop_id,detail_type,description,biz_no,detail_amount,created_at,deleted_at,flag,avialable_amount) values (14,17,1,'\u5546\u54c1\u51fa\u552e','34250527876847164',691106,2020-08-27 19:53:46,1384292845,0,569193),(15,18,2,'\u5546\u54c1\u8d2d\u4e70','65628319757403516',655645,2020-08-27 19:53:46,350582394,0,110706),(16,19,1,'\u5546\u54c1\u51fa\u552e','19636796119968741',808004,2020-08-27 19:53:46,1256861491,0,466446),(17,20,2,'\u5546\u54c1\u8d2d\u4e70','46234490332455651',659574,2020-08-27 19:53:46,486638023,0,178019),(18,21,1,'\u5546\u54c1\u51fa\u552e','49266513315780232',743029,2020-08-27 19:53:46,717553851,0,246508),(19,22,2,'\u5546\u54c1\u8d2d\u4e70','90561178200881606',197382,2020-08-27 19:53:46,809470599,0,821661),(20,23,1,'\u5546\u54c1\u51fa\u552e','47997281259358174',232968,2020-08-27 19:53:46,1356754672,0,883010),(21,24,2,'\u5546\u54c1\u8d2d\u4e70','77079434011691921',162385,2020-08-27 19:53:46,1260205987,0,787554),(22,25,1,'\u5546\u54c1\u51fa\u552e','32080318843531665',429457,2020-08-27 19:53:46,42826607,0,557156),(23,26,2,'\u5546\u54c1\u8d2d\u4e70','15619744594723433',865789,2020-08-27 19:53:46,334998537,0,119933)]
> (Background on this error at: http://sqlalche.me/e/f405)

2020-08-27 19:53:46这种时间有空格，需要带上引号

**Comment by roczzz** [comment]
我用的datatime(1),那个间隔时间有问题

**Comment by roczzz** [comment]
搞好了，是因为python2安装了pymysql,我改成mysql-python能够写入了，现在的又有个问题，order_num(商品出售，商品购买)提示我UnicodeEncodeError: 'latin-1' codec can't encode characters in position 164-167: ordinal not in range(256)

**Comment by gangly** [comment]
metatad.txt 文件内容给下
