### ISSUE TITLE
不知道是什么错误？生成的SQL有语法问题

### ISSUE THREAD

**Issue by gcshine** [gangly/datafaker#50]
UUID||VARCHAR(32)||自增id[:inc(id,1)]
CREATE_USER||VARCHAR(32)||[:enum(file://account_uuid.txt)]
CREATE_TIME||VARCHAR(19)||[:enum(2020-04-05)]
CREATE_ORG||VARCHAR(32)||[:enum(组织1, 组织2)]
CREATE_DEP||VARCHAR(32)||[:enum(部门1, 部门2)]
CHANGE_USER||VARCHAR(32)||[:enum(file://account_uuid.txt)]
ENABLED||CHAR(1)||[:enum(Y)]
REMOVED||CHAR(1)||[:enum(N)]
PRIORITY||DECIMAL(10,0)||顺序号[:decimal(4,2,1)]
REMARK||VARCHAR(32)||
BUSINESS_STATUS||VARCHAR(8)||业务状态[:enum(状态1, 状态2, 状态3, 状态4)]
ID_BUSINESS||VARCHAR(32)||所属业务活动[:enum(春查, 秋查, 安评)]
ID_ITEM||VARCHAR(32)||所属指标（针对安评）
ID_WORK_TYPE||VARCHAR(32)||问题类型（即业务类型）
FIND_DATE||VARCHAR(19)||发现日期
ID_FINDER||VARCHAR(32)||发现人的ID[:enum(file://account_uuid.txt)]
ID_DEPT_FINDER||VARCHAR(32)||发现人所属部门
PHE_CONTENT||VARCHAR(500)||现象描述
ID_BUSINESS_OBJ||VARCHAR(32)||具体业务对象id
ID_BUSINESS_OBJTYPE||VARCHAR(32)||业务对象类型
ID_DEPT_RES||VARCHAR(32)||处理负责部门
ID_PERSON_RES||VARCHAR(32)||处理负责人（审核人）
ID_DEAL||VARCHAR(32)||处理单id
HAZARD_ANALYSIS||VARCHAR(500)||危害分析
PROBLEM_CODE||VARCHAR(32)||编码
ID_WORK_ORDER||VARCHAR(32)||工单ID
ASK_DATE||VARCHAR(19)||要求处理完毕日期[:enum(2020-04-05, 2020-08-08)]

没有为扩展名 .py 找到文件关联
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "C:\ProgramData\Anaconda3\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\ProgramData\Anaconda3\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\ProgramData\Anaconda3\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1054, "Unknown column 'cf12c42e3c844c84b9d4900628893509' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\datafaker-0.7.4-py3.7.egg\datafaker\dbs\basedb.py", line 122, in save
    self.save_data(lines)
  File "C:\ProgramData\Anaconda3\lib\site-packages\datafaker-0.7.4-py3.7.egg\datafaker\dbs\rdbdb.py", line 26, in save_data
    self.save_other_rdb(lines, names_format, column_names)
  File "C:\ProgramData\Anaconda3\lib\site-packages\datafaker-0.7.4-py3.7.egg\datafaker\dbs\rdbdb.py", line 42, in save_other_rdb
    self.session.execute(sql)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\orm\session.py", line 1278, in execute
    clause, params or {}
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1103, in _execute_clauseelement
    distilled_params,
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1288, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1482, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 178, in raise_
    raise exception
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
    cursor, statement, parameters, context
  File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
    cursor.execute(statement, parameters)
  File "C:\ProgramData\Anaconda3\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\ProgramData\Anaconda3\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\ProgramData\Anaconda3\lib\site-packages\MySQLdb\connections.py", line 259, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1054, "Unknown column 'cf12c42e3c844c84b9d4900628893509' in 'field list'")
[SQL: insert into wo_comm_problem (UUID,CREATE_USER,CREATE_TIME,CREATE_ORG,CREATE_DEP,CHANGE_USER,ENABLED,REMOVED,PRIORITY,REMARK,BUSINESS_STATUS,ID_BUSINESS,ID_ITEM,ID_WORK_TYPE,FIND_DATE,ID_FINDER,ID_DEPT_FINDER,PHE_CONTENT,ID_BUSINESS_OBJ,ID_BUSINESS_OBJTYPE,ID_DEPT_RES,ID_PERSON_RES,ID_DEAL,HAZARD_ANALYSIS,PROBLEM_CODE,ID_WORK_ORDER,ASK_DATE) values (1,cf12c42e3c844c84b9d4900628893509,2020-04-05,组织2,部门1,3ddf1219a6c44802bcb073ebd941d8ee,Y,N,49.28,None,状态4,安评,None,None,None,cf12c42e3c844c84b9d4900628893509,None,None,None,None,None,None,None,None,None,None,2020-08-08),(2,0ccfebc5962d46dd916257c0a33201ce,2020-04-05,组织1,部门2,39d9aa650f864e7d9c7e49abc1f521be,Y,N,41.81,None,状态1,安评,None,None,None,0ccfebc5962d46dd916257c0a33201ce,None,None,None,None,None,None,None,None,None,None,2020-08-08),(3,cf4f0c886c4e4fbc955a652487b0ae0e,2020-04-05,组织1,部门2,0ccfebc5962d46dd916257c0a33201ce,Y,N,17.12,None,状态4,秋查,None,None,None,cf12c42e3c844c84b9d4900628893509,None,None,None,None,None,None,None,None,None,None,2020-08-08),(4,0ccfebc5962d46dd916257c0a33201ce,2020-04-05,组织1,部门1,0a5f6438cd9f47ed8d8fa26cfe931672,Y,N,27.3,None,状态1,春查,None,None,None,0ccfebc5962d46dd916257c0a33201ce,None,None,None,None,None,None,None,None,None,None,2020-08-08),(5,cf4f0c886c4e4fbc955a652487b0ae0e,2020-04-05,组织2,部门2,354dac55ffc342c8a21665569754a928,Y,N,55.91,None,状态2,春查,None,None,None,cf4f0c886c4e4fbc955a652487b0ae0e,None,None,None,None,None,None,None,None,None,None,2020-04-05),(6,6cb7d9cfced04873b0827af619e9510b,2020-04-05,组织2,部门1,cf12c42e3c844c84b9d4900628893509,Y,N,75.18,None,状态1,秋查,None,None,None,39d9aa650f864e7d9c7e49abc1f521be,None,None,None,None,None,None,None,None,None,None,2020-04-05),(7,be047b8c3d6048c7820f8ee69ca1002e,2020-04-05,组织1,部门2,be047b8c3d6048c7820f8ee69ca1002e,Y,N,35.61,None,状态4,秋查,None,None,None,ae1eb1fb17e54334b2cb71b0d74ea702,None,None,None,None,None,None,None,None,None,None,2020-08-08),(8,be047b8c3d6048c7820f8ee69ca1002e,2020-04-05,组织1,部门2,6cb7d9cfced04873b0827af619e9510b,Y,N,50.52,None,状态1,安评,None,None,None,cf4f0c886c4e4fbc955a652487b0ae0e,None,None,None,None,None,None,None,None,None,None,2020-04-05),(9,354dac55ffc342c8a21665569754a928,2020-04-05,组织2,部门1,39d9aa650f864e7d9c7e49abc1f521be,Y,N,22.86,None,状态1,秋查,None,None,None,39d9aa650f864e7d9c7e49abc1f521be,None,None,None,None,None,None,None,None,None,None,2020-08-08),(10,cf4f0c886c4e4fbc955a652487b0ae0e,2020-04-05,组织2,部门2,39d9aa650f864e7d9c7e49abc1f521be,Y,N,78.3,None,状态3,秋查,None,None,None,ae1eb1fb17e54334b2cb71b0d74ea702,None,None,None,None,None,None,None,None,None,None,2020-04-05)]

**Comment by gcshine** [comment]
找到问题了，规则文件不能使用大写字母
