### ISSUE TITLE
生成json格式数据到kafka异常

### ISSUE THREAD

**Issue by ccdd4ever** [gangly/datafaker#62]
cli.py line 64，65
  if args.format == JSON_FORMAT and any([args.outprint, args.dbtype in ['file', 'kafka']]):
        raise ParamError('rdb not support for json format')
这里应该是not in ['file', 'kafka']吧

**Comment by gangly** [comment]
是的 这里有点bug, 下个版本修正

**Comment by lyc10031** [comment]
好家伙，我这个报错也是这个原因吧

datafaker file . out1.txt 10  --meta meta.txt --format json
Traceback (most recent call last):
  File "/Users/lyc/Documents/File/m-file/py-file/newpy/venv/lib/python3.6/site-packages/datafaker/cli.py", line 87, in main
    args = parse_args()
  File "/Users/lyc/Documents/File/m-file/py-file/newpy/venv/lib/python3.6/site-packages/datafaker/cli.py", line 65, in parse_args
    raise ParamError('rdb not support for json format')
datafaker.exceptions.ParamError: rdb not support for json format

rdb not support for json format

**Comment by lyc10031** [comment]
很少有人用file 这个参数么？我只想简单的输出到文件中啊😂

**Comment by ccdd4ever** [comment]
> 很少有人用file 这个参数么？我只想简单的输出到文件中啊😂

应该是的，自己改下源码吧
