### ISSUE TITLE
 it's not the same object as sqlalchemy.orm.session.Session

### ISSUE THREAD

**Issue by MinchX** [gangly/datafaker#75]
系统：macOS 11.2.3
环境：Python3.9，mysql8
错误信息：
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/datafaker/cli.py", line 90, in main
    db.do_fake()
  File "/usr/local/lib/python3.9/site-packages/datafaker/utils.py", line 72, in wrapper
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/datafaker/dbs/basedb.py", line 99, in do_fake
    producer.start()
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/local/Cellar/python@3.9/3.9.0_5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'sqlalchemy.orm.session.Session'>: it's not the same object as sqlalchemy.orm.session.Session

Can't pickle <class 'sqlalchemy.orm.session.Session'>: it's not the same object as sqlalchemy.orm.session.Session

**Comment by gangly** [comment]
python3.9 没测试  用3.6试试

**Comment by exqlnet** [comment]
同遇到这个问题

**Comment by AlexBdd** [comment]
我今天也遇到了这个问题，求解决办法
