### ISSUE TITLE
win10 下提示You must supply number of records

### ISSUE THREAD

**Issue by mqqgithub** [gangly/datafaker#83]
cmd下D:\>datafaker file out.txt 10  --meta meta.txt --format json

提示You must supply number of records，已经输入10了啊？

**Comment by gangly** [comment]
命令没用对，需要路径,例如
D:>datafaker file  C:\\ out.txt 10 --meta meta.txt --format json

**Comment by mqqgithub** [comment]
加上路径有报错了
D:\>datafaker file d:\ out.txt 10 --meta meta.txt --format json
Traceback (most recent call last):
  File "D:\dev\python\lib\site-packages\datafaker\cli.py", line 90, in main
    db = load_db_class(args.dbtype)(args)
  File "D:\dev\python\lib\site-packages\datafaker\dbs\basedb.py", line 23, in __init__
    self.schema = self.parse_schema()
  File "D:\dev\python\lib\site-packages\datafaker\dbs\basedb.py", line 159, in parse_schema
    schema = self.parse_meta_schema()
  File "D:\dev\python\lib\site-packages\datafaker\dbs\basedb.py", line 172, in parse_meta_schema
    return self.parse_schema_from_rows(rows)
  File "D:\dev\python\lib\site-packages\datafaker\dbs\basedb.py", line 211, in parse_schema_from_rows
    rets = read_file_lines(rets[0][len(ENUM_FILE):])
  File "D:\dev\python\lib\site-packages\datafaker\utils.py", line 89, in read_file_lines
    contents = read_file(filepath)
  File "D:\dev\python\lib\site-packages\datafaker\utils.py", line 82, in read_file
    raise FileNotFoundError(filepath)
datafaker.exceptions.FileNotFoundError: error, names.txt not found!

error, names.txt not found!
